name_tag: test
data_matrix: test.gz  # /lambda_stor/data/yanyul/Framingham/haplotype_po_framingham/preprocess/expression.all_indiv_w_genotype.tsv.gz
skip_cols: 'probeset_id'
path_to_peertool: /lambda_stor/data/yanyul/softwares/peer/bin/peertool
nfactor: 3  # 40  # the number of PEER factors desired

if_transpose: 'Yes'
indiv_col: None


# if_transpose: 'No'
# indiv_col: 'probeset_id'
