name_tag: 'hapmap3_eur_new'
pop_tag: 'CEU'
individual_list:
  file: '/gpfs/data/im-lab/nas40t2/yanyul/data/hapmap3/relationships_w_pops_041510.txt'
  pop_col: 'population'
  indiv_col: 'IID'
  fam_col: 'FID'
genotypes:
  ped: '/gpfs/data/im-lab/nas40t2/yanyul/data/hapmap3/hapmap3_r3_b36_fwd.consensus.qc.poly.ped'
  map: '/gpfs/data/im-lab/nas40t2/yanyul/data/hapmap3/hapmap3_r3_b36_fwd.consensus.qc.poly.map'
plink1.9: 'plink'  # on CRI: module load gcc/6.2.0; module load plink/1.90
plink_mem_in_mb: 10000
misc_tools_path: '/gpfs/data/im-lab/nas40t2/yanyul/GitHub/misc-tools'

gen_lookup_table:
  chain_file: '/gpfs/data/im-lab/nas40t2/yanyul/data/hg18ToHg19.over.chain.gz'
  target_build: 'b37'
