name_tag: 'hapmap3_eur'
individual_list:
  file: '/gpfs/data/im-lab/nas40t2/yanyul/data/hapmap3/relationships_w_pops_121708.txt'
  pop_col: 'population'
  indiv_col: 'IID'
  fam_col: 'FID'
genotypes:
  ped: '/gpfs/data/im-lab/nas40t2/yanyul/data/hapmap3/hapmap3_r2_b36_fwd.consensus.qc.poly.ped'
  map: '/gpfs/data/im-lab/nas40t2/yanyul/data/hapmap3/hapmap3_r2_b36_fwd.consensus.qc.poly.map'
plink1.9: 'plink'  # on CRI: module load gcc/6.2.0; module load plink/1.90
plink_mem_in_mb: 10000