gwas_tag: 'body_HEIGHTz'
gwas_parquet: '/project2/haky/yanyul/data/SLD4M/{gwas_tag}.sumstats.gz'
gwas_mode: '--as_text_gz variant_id:SNP b:Beta b_se:se'
gwas_formatted: 'output/{gwas_tag}.formated_gwas.mat'

outdir: 'output_new_agg'

SLD4M: 
  path_to_scripts: '/project2/haky/yanyul/github_external/SLD4M'
  l2l4: '/project2/haky/yanyul/data/SLD4M/baselineLD.1kg.l2l4.mat'
  # l2l4: '/project2/haky/yanyul/data/SLD4M/baselineLD.1kg.common.l2l4.mat'
path_to_run_script: '/project2/haky/yanyul/GitHub/misc-tools/est_polygenicity/scripts'
